export interface Stage {
  id: number;
  name: string;
  enemyGrubMultiplier: number;
  counterChance: number;
  enemyLevel: number;
  hideoutHp: number;
  jailhouseHp: number;
  firstClearBounty: number;
}

export const STAGES: Stage[] = [
  {
    id: 1,
    name: "Tumbleweed Flats",
    enemyGrubMultiplier: 0.6,
    counterChance: 0.1,
    enemyLevel: 1,
    hideoutHp: 300,
    jailhouseHp: 600,
    firstClearBounty: 20,
  },
  {
    id: 2,
    name: "Quiet Crossing",
    enemyGrubMultiplier: 0.7,
    counterChance: 0.2,
    enemyLevel: 1,
    hideoutHp: 400,
    jailhouseHp: 550,
    firstClearBounty: 30,
  },
  {
    id: 3,
    name: "Dusty Gulch",
    enemyGrubMultiplier: 0.8,
    counterChance: 0.3,
    enemyLevel: 1,
    hideoutHp: 500,
    jailhouseHp: 500,
    firstClearBounty: 40,
  },
  {
    id: 4,
    name: "Rattlesnake Pass",
    enemyGrubMultiplier: 0.9,
    counterChance: 0.45,
    enemyLevel: 1,
    hideoutHp: 600,
    jailhouseHp: 500,
    firstClearBounty: 55,
  },
  {
    id: 5,
    name: "Coyote Creek",
    enemyGrubMultiplier: 1,
    counterChance: 0.55,
    enemyLevel: 2,
    hideoutHp: 700,
    jailhouseHp: 500,
    firstClearBounty: 70,
  },
  {
    id: 6,
    name: "Sunbaked Draw",
    enemyGrubMultiplier: 1.15,
    counterChance: 0.7,
    enemyLevel: 3,
    hideoutHp: 800,
    jailhouseHp: 500,
    firstClearBounty: 90,
  },
  {
    id: 7,
    name: "Cutter's Outpost",
    enemyGrubMultiplier: 1.25,
    counterChance: 0.8,
    enemyLevel: 4,
    hideoutHp: 900,
    jailhouseHp: 500,
    firstClearBounty: 120,
  },
  {
    id: 8,
    name: "Widow Rock",
    enemyGrubMultiplier: 1.35,
    counterChance: 0.85,
    enemyLevel: 4,
    hideoutHp: 1050,
    jailhouseHp: 450,
    firstClearBounty: 150,
  },
  {
    id: 9,
    name: "Splinter Row",
    enemyGrubMultiplier: 1.45,
    counterChance: 0.9,
    enemyLevel: 5,
    hideoutHp: 1200,
    jailhouseHp: 450,
    firstClearBounty: 190,
  },
  {
    id: 10,
    name: "Last Water Camp",
    enemyGrubMultiplier: 1.55,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1400,
    jailhouseHp: 400,
    firstClearBounty: 240,
  },
  {
    id: 11,
    name: "The Cutter's Den",
    enemyGrubMultiplier: 1.8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1850,
    jailhouseHp: 380,
    firstClearBounty: 270,
  },
  {
    id: 12,
    name: "Dead Man's Mesa",
    enemyGrubMultiplier: 1.9,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2000,
    jailhouseHp: 360,
    firstClearBounty: 285,
  },
  {
    id: 13,
    name: "Black Hat Canyon",
    enemyGrubMultiplier: 2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2150,
    jailhouseHp: 360,
    firstClearBounty: 300,
  },
  {
    id: 14,
    name: "Vulture Ridge",
    enemyGrubMultiplier: 2.1,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2300,
    jailhouseHp: 340,
    firstClearBounty: 320,
  },
  {
    id: 15,
    name: "Iron Horse Depot",
    enemyGrubMultiplier: 2.2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2450,
    jailhouseHp: 340,
    firstClearBounty: 340,
  },
  {
    id: 16,
    name: "Sundown Standoff",
    enemyGrubMultiplier: 2.35,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2600,
    jailhouseHp: 320,
    firstClearBounty: 360,
  },
  {
    id: 17,
    name: "Buzzard Flat",
    enemyGrubMultiplier: 2.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2750,
    jailhouseHp: 320,
    firstClearBounty: 380,
  },
  {
    id: 18,
    name: "Broken Wheel Camp",
    enemyGrubMultiplier: 2.55,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2900,
    jailhouseHp: 300,
    firstClearBounty: 405,
  },
  {
    id: 19,
    name: "Skinner's Gulch",
    enemyGrubMultiplier: 2.65,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3050,
    jailhouseHp: 300,
    firstClearBounty: 430,
  },
  {
    id: 20,
    name: "The Bone Orchard",
    enemyGrubMultiplier: 2.75,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3200,
    jailhouseHp: 280,
    firstClearBounty: 455,
  },
  {
    id: 21,
    name: "Scavenger's Row",
    enemyGrubMultiplier: 2.9,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3350,
    jailhouseHp: 280,
    firstClearBounty: 480,
  },
  {
    id: 22,
    name: "Carrion Pass",
    enemyGrubMultiplier: 3,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3500,
    jailhouseHp: 260,
    firstClearBounty: 510,
  },
  {
    id: 23,
    name: "Vulture's Roost",
    enemyGrubMultiplier: 3.1,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3650,
    jailhouseHp: 260,
    firstClearBounty: 540,
  },
  {
    id: 24,
    name: "Talon Ridge",
    enemyGrubMultiplier: 3.2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3800,
    jailhouseHp: 240,
    firstClearBounty: 570,
  },
  {
    id: 25,
    name: "The Molting Grounds",
    enemyGrubMultiplier: 3.3,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3950,
    jailhouseHp: 240,
    firstClearBounty: 605,
  },
  {
    id: 26,
    name: "Syndicate Row",
    enemyGrubMultiplier: 3.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 4100,
    jailhouseHp: 220,
    firstClearBounty: 640,
  },
  {
    id: 27,
    name: "The Vulture's Nest",
    enemyGrubMultiplier: 3.65,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 4550,
    jailhouseHp: 200,
    firstClearBounty: 715,
  },
  {
    id: 28,
    name: "Rustler's Hollow",
    enemyGrubMultiplier: 3.75,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 4700,
    jailhouseHp: 180,
    firstClearBounty: 760,
  },
  {
    id: 29,
    name: "Powder Canyon",
    enemyGrubMultiplier: 3.85,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 4850,
    jailhouseHp: 180,
    firstClearBounty: 805,
  },
  {
    id: 30,
    name: "Deadline Junction",
    enemyGrubMultiplier: 3.95,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5000,
    jailhouseHp: 160,
    firstClearBounty: 855,
  },
  {
    id: 31,
    name: "Ironclad Yard",
    enemyGrubMultiplier: 4.1,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5150,
    jailhouseHp: 160,
    firstClearBounty: 905,
  },
  {
    id: 32,
    name: "Railhead Reckoning",
    enemyGrubMultiplier: 4.2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5300,
    jailhouseHp: 150,
    firstClearBounty: 960,
  },
  {
    id: 33,
    name: "Spur Line Camp",
    enemyGrubMultiplier: 4.3,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5450,
    jailhouseHp: 150,
    firstClearBounty: 1020,
  },
  {
    id: 34,
    name: "Trestle Hollow",
    enemyGrubMultiplier: 4.4,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5600,
    jailhouseHp: 150,
    firstClearBounty: 1080,
  },
  {
    id: 35,
    name: "Cinder Yard",
    enemyGrubMultiplier: 4.5,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5750,
    jailhouseHp: 150,
    firstClearBounty: 1145,
  },
  {
    id: 36,
    name: "Boiler Row",
    enemyGrubMultiplier: 4.65,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 5900,
    jailhouseHp: 150,
    firstClearBounty: 1215,
  },
  {
    id: 37,
    name: "The Switchback",
    enemyGrubMultiplier: 4.75,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6050,
    jailhouseHp: 150,
    firstClearBounty: 1290,
  },
  {
    id: 38,
    name: "Coalbed Flats",
    enemyGrubMultiplier: 4.85,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6200,
    jailhouseHp: 150,
    firstClearBounty: 1365,
  },
  {
    id: 39,
    name: "Freight Road",
    enemyGrubMultiplier: 4.95,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6350,
    jailhouseHp: 150,
    firstClearBounty: 1445,
  },
  {
    id: 40,
    name: "Signal Hill",
    enemyGrubMultiplier: 5.05,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6500,
    jailhouseHp: 150,
    firstClearBounty: 1530,
  },
  {
    id: 41,
    name: "The Turntable",
    enemyGrubMultiplier: 5.2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6650,
    jailhouseHp: 150,
    firstClearBounty: 1620,
  },
  {
    id: 42,
    name: "Rail Spike Ridge",
    enemyGrubMultiplier: 5.3,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6800,
    jailhouseHp: 150,
    firstClearBounty: 1715,
  },
  {
    id: 43,
    name: "Depot Row",
    enemyGrubMultiplier: 5.4,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 6950,
    jailhouseHp: 150,
    firstClearBounty: 1820,
  },
  {
    id: 44,
    name: "Steam Gate",
    enemyGrubMultiplier: 5.5,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 7100,
    jailhouseHp: 150,
    firstClearBounty: 1930,
  },
  {
    id: 45,
    name: "The Iron Horse Yard",
    enemyGrubMultiplier: 5.7,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 7550,
    jailhouseHp: 150,
    firstClearBounty: 2160,
  },
  {
    id: 46,
    name: "Blackwater Camp",
    enemyGrubMultiplier: 5.85,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 7700,
    jailhouseHp: 150,
    firstClearBounty: 2290,
  },
  {
    id: 47,
    name: "Silver Vein Road",
    enemyGrubMultiplier: 5.95,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 7850,
    jailhouseHp: 150,
    firstClearBounty: 2425,
  },
  {
    id: 48,
    name: "Foreman's Bluff",
    enemyGrubMultiplier: 6.05,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8000,
    jailhouseHp: 150,
    firstClearBounty: 2570,
  },
  {
    id: 49,
    name: "The Company Wall",
    enemyGrubMultiplier: 6.15,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8150,
    jailhouseHp: 150,
    firstClearBounty: 2725,
  },
  {
    id: 50,
    name: "Blackwater Reckoning",
    enemyGrubMultiplier: 6.25,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8300,
    jailhouseHp: 150,
    firstClearBounty: 2890,
  },
  {
    id: 51,
    name: "Claim Jumper's Camp",
    enemyGrubMultiplier: 6.4,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8450,
    jailhouseHp: 150,
    firstClearBounty: 3065,
  },
  {
    id: 52,
    name: "Silt Bend",
    enemyGrubMultiplier: 6.5,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8600,
    jailhouseHp: 150,
    firstClearBounty: 3250,
  },
  {
    id: 53,
    name: "The Assay Office",
    enemyGrubMultiplier: 6.6,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8750,
    jailhouseHp: 150,
    firstClearBounty: 3445,
  },
  {
    id: 54,
    name: "Powder Magazine",
    enemyGrubMultiplier: 6.7,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 8900,
    jailhouseHp: 150,
    firstClearBounty: 3650,
  },
  {
    id: 55,
    name: "Shaft Row",
    enemyGrubMultiplier: 6.8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 9050,
    jailhouseHp: 150,
    firstClearBounty: 3870,
  },
  {
    id: 56,
    name: "Sluice Gate",
    enemyGrubMultiplier: 6.95,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 9200,
    jailhouseHp: 150,
    firstClearBounty: 4100,
  },
  {
    id: 57,
    name: "Blackwater Gate",
    enemyGrubMultiplier: 7.15,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 9650,
    jailhouseHp: 150,
    firstClearBounty: 4590,
  },
  {
    id: 58,
    name: "Vane's Outer Watch",
    enemyGrubMultiplier: 7.25,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 9800,
    jailhouseHp: 150,
    firstClearBounty: 4865,
  },
  {
    id: 59,
    name: "The Barbed Line",
    enemyGrubMultiplier: 7.35,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 9950,
    jailhouseHp: 150,
    firstClearBounty: 5155,
  },
  {
    id: 60,
    name: "Cordell's Ranch",
    enemyGrubMultiplier: 7.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10100,
    jailhouseHp: 150,
    firstClearBounty: 5465,
  },
  {
    id: 61,
    name: "The Last Gate",
    enemyGrubMultiplier: 7.6,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10250,
    jailhouseHp: 150,
    firstClearBounty: 5795,
  },
  {
    id: 62,
    name: "Cordell's Doorstep",
    enemyGrubMultiplier: 7.7,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10400,
    jailhouseHp: 150,
    firstClearBounty: 6145,
  },
  {
    id: 63,
    name: "The Bunkhouse Row",
    enemyGrubMultiplier: 7.8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10550,
    jailhouseHp: 150,
    firstClearBounty: 6515,
  },
  {
    id: 64,
    name: "Powder Hill",
    enemyGrubMultiplier: 7.9,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10700,
    jailhouseHp: 150,
    firstClearBounty: 6905,
  },
  {
    id: 65,
    name: "The Foreman's Yard",
    enemyGrubMultiplier: 8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 10850,
    jailhouseHp: 150,
    firstClearBounty: 7320,
  },
  {
    id: 66,
    name: "Vane's Armory",
    enemyGrubMultiplier: 8.15,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 11000,
    jailhouseHp: 150,
    firstClearBounty: 7760,
  },
  {
    id: 67,
    name: "The Long Corral",
    enemyGrubMultiplier: 8.25,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 11150,
    jailhouseHp: 150,
    firstClearBounty: 8225,
  },
  {
    id: 68,
    name: "Watchtower Ridge",
    enemyGrubMultiplier: 8.35,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 11300,
    jailhouseHp: 150,
    firstClearBounty: 8720,
  },
  {
    id: 69,
    name: "The Inner Gate",
    enemyGrubMultiplier: 8.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 11450,
    jailhouseHp: 150,
    firstClearBounty: 9245,
  },
  {
    id: 70,
    name: "Vane's Courtyard",
    enemyGrubMultiplier: 8.55,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 11600,
    jailhouseHp: 150,
    firstClearBounty: 9800,
  },
  {
    id: 71,
    name: "Vane's Last Stand",
    enemyGrubMultiplier: 8.8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 12050,
    jailhouseHp: 150,
    firstClearBounty: 10975,
  },
];

export const REPLAY_BOUNTY_RATIO = 0.5;
export const DEFEAT_BOUNTY = 10;
