export interface Stage {
  id: number;
  name: string;
  enemyGrubMultiplier: number;
  counterChance: number;
  enemyLevel: number;
  hideoutHp: number;
  jailhouseHp: number;
  firstClearBounty: number;
}

export const STAGES: Stage[] = [
  {
    id: 1,
    name: "Tumbleweed Flats",
    enemyGrubMultiplier: 0.5,
    counterChance: 0.05,
    enemyLevel: 1,
    hideoutHp: 260,
    jailhouseHp: 600,
    firstClearBounty: 15,
  },
  {
    id: 2,
    name: "Quiet Crossing",
    enemyGrubMultiplier: 0.52,
    counterChance: 0.09,
    enemyLevel: 1,
    hideoutHp: 310,
    jailhouseHp: 600,
    firstClearBounty: 15,
  },
  {
    id: 3,
    name: "Dusty Gulch",
    enemyGrubMultiplier: 0.54,
    counterChance: 0.12,
    enemyLevel: 1,
    hideoutHp: 360,
    jailhouseHp: 592,
    firstClearBounty: 15,
  },
  {
    id: 4,
    name: "Rattlesnake Pass",
    enemyGrubMultiplier: 0.56,
    counterChance: 0.16,
    enemyLevel: 1,
    hideoutHp: 410,
    jailhouseHp: 592,
    firstClearBounty: 20,
  },
  {
    id: 5,
    name: "Coyote Creek",
    enemyGrubMultiplier: 0.58,
    counterChance: 0.19,
    enemyLevel: 1,
    hideoutHp: 460,
    jailhouseHp: 584,
    firstClearBounty: 20,
  },
  {
    id: 6,
    name: "Sunbaked Draw",
    enemyGrubMultiplier: 0.61,
    counterChance: 0.23,
    enemyLevel: 1,
    hideoutHp: 510,
    jailhouseHp: 584,
    firstClearBounty: 20,
  },
  {
    id: 7,
    name: "Cutter's Outpost",
    enemyGrubMultiplier: 0.63,
    counterChance: 0.26,
    enemyLevel: 2,
    hideoutHp: 560,
    jailhouseHp: 576,
    firstClearBounty: 20,
  },
  {
    id: 8,
    name: "Widow Rock",
    enemyGrubMultiplier: 0.65,
    counterChance: 0.3,
    enemyLevel: 2,
    hideoutHp: 610,
    jailhouseHp: 576,
    firstClearBounty: 20,
  },
  {
    id: 9,
    name: "Splinter Row",
    enemyGrubMultiplier: 0.67,
    counterChance: 0.33,
    enemyLevel: 2,
    hideoutHp: 660,
    jailhouseHp: 568,
    firstClearBounty: 25,
  },
  {
    id: 10,
    name: "Last Water Camp",
    enemyGrubMultiplier: 0.69,
    counterChance: 0.37,
    enemyLevel: 2,
    hideoutHp: 710,
    jailhouseHp: 568,
    firstClearBounty: 25,
  },
  {
    id: 11,
    name: "The Cutter's Den",
    enemyGrubMultiplier: 0.77,
    counterChance: 0.4,
    enemyLevel: 2,
    hideoutHp: 1060,
    jailhouseHp: 540,
    firstClearBounty: 30,
  },
  {
    id: 12,
    name: "Dead Man's Mesa",
    enemyGrubMultiplier: 0.79,
    counterChance: 0.44,
    enemyLevel: 2,
    hideoutHp: 1110,
    jailhouseHp: 540,
    firstClearBounty: 30,
  },
  {
    id: 13,
    name: "Black Hat Canyon",
    enemyGrubMultiplier: 0.81,
    counterChance: 0.47,
    enemyLevel: 2,
    hideoutHp: 1160,
    jailhouseHp: 532,
    firstClearBounty: 30,
  },
  {
    id: 14,
    name: "Vulture Ridge",
    enemyGrubMultiplier: 0.83,
    counterChance: 0.51,
    enemyLevel: 2,
    hideoutHp: 1210,
    jailhouseHp: 532,
    firstClearBounty: 35,
  },
  {
    id: 15,
    name: "Iron Horse Depot",
    enemyGrubMultiplier: 0.85,
    counterChance: 0.54,
    enemyLevel: 3,
    hideoutHp: 1260,
    jailhouseHp: 524,
    firstClearBounty: 35,
  },
  {
    id: 16,
    name: "Sundown Standoff",
    enemyGrubMultiplier: 0.88,
    counterChance: 0.58,
    enemyLevel: 3,
    hideoutHp: 1310,
    jailhouseHp: 524,
    firstClearBounty: 40,
  },
  {
    id: 17,
    name: "Buzzard Flat",
    enemyGrubMultiplier: 0.9,
    counterChance: 0.61,
    enemyLevel: 3,
    hideoutHp: 1360,
    jailhouseHp: 516,
    firstClearBounty: 40,
  },
  {
    id: 18,
    name: "Broken Wheel Camp",
    enemyGrubMultiplier: 0.92,
    counterChance: 0.65,
    enemyLevel: 3,
    hideoutHp: 1410,
    jailhouseHp: 516,
    firstClearBounty: 45,
  },
  {
    id: 19,
    name: "Skinner's Gulch",
    enemyGrubMultiplier: 0.94,
    counterChance: 0.68,
    enemyLevel: 3,
    hideoutHp: 1460,
    jailhouseHp: 508,
    firstClearBounty: 45,
  },
  {
    id: 20,
    name: "The Bone Orchard",
    enemyGrubMultiplier: 0.96,
    counterChance: 0.72,
    enemyLevel: 3,
    hideoutHp: 1510,
    jailhouseHp: 508,
    firstClearBounty: 50,
  },
  {
    id: 21,
    name: "Scavenger's Row",
    enemyGrubMultiplier: 0.99,
    counterChance: 0.75,
    enemyLevel: 3,
    hideoutHp: 1560,
    jailhouseHp: 500,
    firstClearBounty: 50,
  },
  {
    id: 22,
    name: "Carrion Pass",
    enemyGrubMultiplier: 1.01,
    counterChance: 0.75,
    enemyLevel: 3,
    hideoutHp: 1610,
    jailhouseHp: 500,
    firstClearBounty: 55,
  },
  {
    id: 23,
    name: "Vulture's Roost",
    enemyGrubMultiplier: 1.03,
    counterChance: 0.75,
    enemyLevel: 3,
    hideoutHp: 1660,
    jailhouseHp: 492,
    firstClearBounty: 55,
  },
  {
    id: 24,
    name: "Talon Ridge",
    enemyGrubMultiplier: 1.05,
    counterChance: 0.75,
    enemyLevel: 3,
    hideoutHp: 1710,
    jailhouseHp: 492,
    firstClearBounty: 60,
  },
  {
    id: 25,
    name: "The Molting Grounds",
    enemyGrubMultiplier: 1.07,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 1760,
    jailhouseHp: 484,
    firstClearBounty: 65,
  },
  {
    id: 26,
    name: "Syndicate Row",
    enemyGrubMultiplier: 1.1,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 1810,
    jailhouseHp: 484,
    firstClearBounty: 65,
  },
  {
    id: 27,
    name: "The Vulture's Nest",
    enemyGrubMultiplier: 1.17,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2160,
    jailhouseHp: 456,
    firstClearBounty: 75,
  },
  {
    id: 28,
    name: "Rustler's Hollow",
    enemyGrubMultiplier: 1.19,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2210,
    jailhouseHp: 456,
    firstClearBounty: 80,
  },
  {
    id: 29,
    name: "Powder Canyon",
    enemyGrubMultiplier: 1.21,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2260,
    jailhouseHp: 448,
    firstClearBounty: 85,
  },
  {
    id: 30,
    name: "Deadline Junction",
    enemyGrubMultiplier: 1.23,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2310,
    jailhouseHp: 448,
    firstClearBounty: 90,
  },
  {
    id: 31,
    name: "Ironclad Yard",
    enemyGrubMultiplier: 1.26,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2360,
    jailhouseHp: 440,
    firstClearBounty: 95,
  },
  {
    id: 32,
    name: "Railhead Reckoning",
    enemyGrubMultiplier: 1.28,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2410,
    jailhouseHp: 440,
    firstClearBounty: 100,
  },
  {
    id: 33,
    name: "Spur Line Camp",
    enemyGrubMultiplier: 1.3,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2460,
    jailhouseHp: 432,
    firstClearBounty: 110,
  },
  {
    id: 34,
    name: "Trestle Hollow",
    enemyGrubMultiplier: 1.32,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2510,
    jailhouseHp: 432,
    firstClearBounty: 115,
  },
  {
    id: 35,
    name: "Cinder Yard",
    enemyGrubMultiplier: 1.34,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2560,
    jailhouseHp: 424,
    firstClearBounty: 120,
  },
  {
    id: 36,
    name: "Boiler Row",
    enemyGrubMultiplier: 1.37,
    counterChance: 0.75,
    enemyLevel: 4,
    hideoutHp: 2610,
    jailhouseHp: 424,
    firstClearBounty: 130,
  },
  {
    id: 37,
    name: "The Switchback",
    enemyGrubMultiplier: 1.39,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2660,
    jailhouseHp: 416,
    firstClearBounty: 135,
  },
  {
    id: 38,
    name: "Coalbed Flats",
    enemyGrubMultiplier: 1.41,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2710,
    jailhouseHp: 416,
    firstClearBounty: 145,
  },
  {
    id: 39,
    name: "Freight Road",
    enemyGrubMultiplier: 1.43,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2760,
    jailhouseHp: 408,
    firstClearBounty: 150,
  },
  {
    id: 40,
    name: "Signal Hill",
    enemyGrubMultiplier: 1.45,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2810,
    jailhouseHp: 408,
    firstClearBounty: 160,
  },
  {
    id: 41,
    name: "The Turntable",
    enemyGrubMultiplier: 1.48,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2860,
    jailhouseHp: 400,
    firstClearBounty: 170,
  },
  {
    id: 42,
    name: "Rail Spike Ridge",
    enemyGrubMultiplier: 1.5,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2910,
    jailhouseHp: 400,
    firstClearBounty: 180,
  },
  {
    id: 43,
    name: "Depot Row",
    enemyGrubMultiplier: 1.52,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 2960,
    jailhouseHp: 392,
    firstClearBounty: 190,
  },
  {
    id: 44,
    name: "Steam Gate",
    enemyGrubMultiplier: 1.54,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3010,
    jailhouseHp: 392,
    firstClearBounty: 200,
  },
  {
    id: 45,
    name: "The Iron Horse Yard",
    enemyGrubMultiplier: 1.61,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3360,
    jailhouseHp: 364,
    firstClearBounty: 230,
  },
  {
    id: 46,
    name: "Blackwater Camp",
    enemyGrubMultiplier: 1.64,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3410,
    jailhouseHp: 364,
    firstClearBounty: 245,
  },
  {
    id: 47,
    name: "Silver Vein Road",
    enemyGrubMultiplier: 1.66,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3460,
    jailhouseHp: 356,
    firstClearBounty: 260,
  },
  {
    id: 48,
    name: "Foreman's Bluff",
    enemyGrubMultiplier: 1.68,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3510,
    jailhouseHp: 356,
    firstClearBounty: 275,
  },
  {
    id: 49,
    name: "The Company Wall",
    enemyGrubMultiplier: 1.7,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3560,
    jailhouseHp: 348,
    firstClearBounty: 290,
  },
  {
    id: 50,
    name: "Blackwater Reckoning",
    enemyGrubMultiplier: 1.72,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3610,
    jailhouseHp: 348,
    firstClearBounty: 305,
  },
  {
    id: 51,
    name: "Claim Jumper's Camp",
    enemyGrubMultiplier: 1.75,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3660,
    jailhouseHp: 340,
    firstClearBounty: 325,
  },
  {
    id: 52,
    name: "Silt Bend",
    enemyGrubMultiplier: 1.77,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3710,
    jailhouseHp: 340,
    firstClearBounty: 340,
  },
  {
    id: 53,
    name: "The Assay Office",
    enemyGrubMultiplier: 1.79,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3760,
    jailhouseHp: 332,
    firstClearBounty: 360,
  },
  {
    id: 54,
    name: "Powder Magazine",
    enemyGrubMultiplier: 1.81,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3810,
    jailhouseHp: 332,
    firstClearBounty: 380,
  },
  {
    id: 55,
    name: "Shaft Row",
    enemyGrubMultiplier: 1.83,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3860,
    jailhouseHp: 324,
    firstClearBounty: 405,
  },
  {
    id: 56,
    name: "Sluice Gate",
    enemyGrubMultiplier: 1.86,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 3910,
    jailhouseHp: 324,
    firstClearBounty: 430,
  },
  {
    id: 57,
    name: "Blackwater Gate",
    enemyGrubMultiplier: 1.93,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4260,
    jailhouseHp: 296,
    firstClearBounty: 490,
  },
  {
    id: 58,
    name: "Vane's Outer Watch",
    enemyGrubMultiplier: 1.95,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4310,
    jailhouseHp: 296,
    firstClearBounty: 520,
  },
  {
    id: 59,
    name: "The Barbed Line",
    enemyGrubMultiplier: 1.97,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4360,
    jailhouseHp: 288,
    firstClearBounty: 550,
  },
  {
    id: 60,
    name: "Cordell's Ranch",
    enemyGrubMultiplier: 1.99,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4410,
    jailhouseHp: 288,
    firstClearBounty: 585,
  },
  {
    id: 61,
    name: "The Last Gate",
    enemyGrubMultiplier: 2.02,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4460,
    jailhouseHp: 280,
    firstClearBounty: 615,
  },
  {
    id: 62,
    name: "Cordell's Doorstep",
    enemyGrubMultiplier: 2.04,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4510,
    jailhouseHp: 280,
    firstClearBounty: 650,
  },
  {
    id: 63,
    name: "The Bunkhouse Row",
    enemyGrubMultiplier: 2.06,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4560,
    jailhouseHp: 272,
    firstClearBounty: 690,
  },
  {
    id: 64,
    name: "Powder Hill",
    enemyGrubMultiplier: 2.08,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4610,
    jailhouseHp: 272,
    firstClearBounty: 730,
  },
  {
    id: 65,
    name: "The Foreman's Yard",
    enemyGrubMultiplier: 2.1,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4660,
    jailhouseHp: 264,
    firstClearBounty: 775,
  },
  {
    id: 66,
    name: "Vane's Armory",
    enemyGrubMultiplier: 2.13,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4710,
    jailhouseHp: 264,
    firstClearBounty: 820,
  },
  {
    id: 67,
    name: "The Long Corral",
    enemyGrubMultiplier: 2.15,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4760,
    jailhouseHp: 256,
    firstClearBounty: 865,
  },
  {
    id: 68,
    name: "Watchtower Ridge",
    enemyGrubMultiplier: 2.17,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4810,
    jailhouseHp: 256,
    firstClearBounty: 915,
  },
  {
    id: 69,
    name: "The Inner Gate",
    enemyGrubMultiplier: 2.19,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4860,
    jailhouseHp: 248,
    firstClearBounty: 970,
  },
  {
    id: 70,
    name: "Vane's Courtyard",
    enemyGrubMultiplier: 2.21,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 4910,
    jailhouseHp: 248,
    firstClearBounty: 1025,
  },
  {
    id: 71,
    name: "Vane's Last Stand",
    enemyGrubMultiplier: 2.29,
    counterChance: 0.75,
    enemyLevel: 5,
    hideoutHp: 5260,
    jailhouseHp: 220,
    firstClearBounty: 1180,
  },
];

export const REPLAY_BOUNTY_RATIO = 0.5;
export const DEFEAT_BOUNTY = 10;
