export interface Stage {
  id: number;
  name: string;
  enemyGrubMultiplier: number;
  counterChance: number;
  enemyLevel: number;
  hideoutHp: number;
  jailhouseHp: number;
  firstClearBounty: number;
}

export const STAGES: Stage[] = [
  {
    id: 1,
    name: "Tumbleweed Flats",
    enemyGrubMultiplier: 0.6,
    counterChance: 0.1,
    enemyLevel: 1,
    hideoutHp: 300,
    jailhouseHp: 600,
    firstClearBounty: 20,
  },
  {
    id: 2,
    name: "Quiet Crossing",
    enemyGrubMultiplier: 0.75,
    counterChance: 0.2,
    enemyLevel: 1,
    hideoutHp: 400,
    jailhouseHp: 550,
    firstClearBounty: 30,
  },
  {
    id: 3,
    name: "Dusty Gulch",
    enemyGrubMultiplier: 0.9,
    counterChance: 0.3,
    enemyLevel: 1,
    hideoutHp: 500,
    jailhouseHp: 500,
    firstClearBounty: 40,
  },
  {
    id: 4,
    name: "Rattlesnake Pass",
    enemyGrubMultiplier: 1.0,
    counterChance: 0.45,
    enemyLevel: 1,
    hideoutHp: 600,
    jailhouseHp: 500,
    firstClearBounty: 55,
  },
  {
    id: 5,
    name: "Coyote Creek",
    enemyGrubMultiplier: 1.1,
    counterChance: 0.55,
    enemyLevel: 2,
    hideoutHp: 700,
    jailhouseHp: 500,
    firstClearBounty: 70,
  },
  {
    id: 6,
    name: "Dead Man's Mesa",
    enemyGrubMultiplier: 1.2,
    counterChance: 0.7,
    enemyLevel: 3,
    hideoutHp: 800,
    jailhouseHp: 500,
    firstClearBounty: 90,
  },
  {
    id: 7,
    name: "Black Hat Canyon",
    enemyGrubMultiplier: 1.35,
    counterChance: 0.8,
    enemyLevel: 4,
    hideoutHp: 900,
    jailhouseHp: 500,
    firstClearBounty: 120,
  },
  {
    id: 8,
    name: "Vulture Ridge",
    enemyGrubMultiplier: 1.5,
    counterChance: 0.85,
    enemyLevel: 4,
    hideoutHp: 1050,
    jailhouseHp: 450,
    firstClearBounty: 150,
  },
  {
    id: 9,
    name: "Iron Horse Depot",
    enemyGrubMultiplier: 1.65,
    counterChance: 0.9,
    enemyLevel: 5,
    hideoutHp: 1200,
    jailhouseHp: 450,
    firstClearBounty: 190,
  },
  {
    id: 10,
    name: "Sundown Standoff",
    enemyGrubMultiplier: 1.8,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1400,
    jailhouseHp: 400,
    firstClearBounty: 240,
  },
  {
    id: 11,
    name: "Rustler's Hollow",
    enemyGrubMultiplier: 1.9,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1550,
    jailhouseHp: 400,
    firstClearBounty: 270,
  },
  {
    id: 12,
    name: "Powder Canyon",
    enemyGrubMultiplier: 2.0,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1700,
    jailhouseHp: 380,
    firstClearBounty: 310,
  },
  {
    id: 13,
    name: "Deadline Junction",
    enemyGrubMultiplier: 2.1,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 1850,
    jailhouseHp: 380,
    firstClearBounty: 355,
  },
  {
    id: 14,
    name: "Ironclad Yard",
    enemyGrubMultiplier: 2.2,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2000,
    jailhouseHp: 360,
    firstClearBounty: 405,
  },
  {
    id: 15,
    name: "Railhead Reckoning",
    enemyGrubMultiplier: 2.35,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2200,
    jailhouseHp: 360,
    firstClearBounty: 460,
  },
  {
    id: 16,
    name: "Blackwater Camp",
    enemyGrubMultiplier: 2.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2350,
    jailhouseHp: 340,
    firstClearBounty: 500,
  },
  {
    id: 17,
    name: "Silver Vein Road",
    enemyGrubMultiplier: 2.55,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2500,
    jailhouseHp: 340,
    firstClearBounty: 540,
  },
  {
    id: 18,
    name: "Foreman's Bluff",
    enemyGrubMultiplier: 2.65,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2650,
    jailhouseHp: 320,
    firstClearBounty: 580,
  },
  {
    id: 19,
    name: "The Company Wall",
    enemyGrubMultiplier: 2.75,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 2800,
    jailhouseHp: 320,
    firstClearBounty: 630,
  },
  {
    id: 20,
    name: "Blackwater Reckoning",
    enemyGrubMultiplier: 2.9,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3000,
    jailhouseHp: 300,
    firstClearBounty: 690,
  },
  {
    id: 21,
    name: "Vane's Outer Watch",
    enemyGrubMultiplier: 3.0,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3150,
    jailhouseHp: 300,
    firstClearBounty: 740,
  },
  {
    id: 22,
    name: "The Barbed Line",
    enemyGrubMultiplier: 3.15,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3300,
    jailhouseHp: 280,
    firstClearBounty: 800,
  },
  {
    id: 23,
    name: "Cordell's Ranch",
    enemyGrubMultiplier: 3.3,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3500,
    jailhouseHp: 280,
    firstClearBounty: 860,
  },
  {
    id: 24,
    name: "The Last Gate",
    enemyGrubMultiplier: 3.45,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 3700,
    jailhouseHp: 260,
    firstClearBounty: 930,
  },
  {
    id: 25,
    name: "Vane's Last Stand",
    enemyGrubMultiplier: 3.6,
    counterChance: 0.95,
    enemyLevel: 5,
    hideoutHp: 4000,
    jailhouseHp: 260,
    firstClearBounty: 1000,
  },
];

export const REPLAY_BOUNTY_RATIO = 0.5;
export const DEFEAT_BOUNTY = 10;
